apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  labels:
    type: frontend
  namespace: kube-system
spec:
  template:
    metadata:
      name: elasticsearch
      labels:
        type: frontend
    spec:
      containers:
        - name: elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      type: frontend