apiVersion: v1
kind: Service
metadata:
  labels:
    app: fileserver
  name: gop-fs-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31200
  selector:
    app: fileserver
  type: NodePort
status:
  loadBalancer: {}