apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  jobTemplate:
    metadata:
      name: dice
    spec:
      activeDeadlineSeconds: 20
      template:
        spec:
          containers:
          -  image: kodekloud/throw-dice
             name: throw-dice
          restartPolicy: OnFailure
      backoffLimit: 25
      completions: 1
  schedule: "* * * * *"
status: {}